import test from "node:test";
import assert from "node:assert/strict";
import { fileURLToPath } from "node:url";

import { analyze } from "../src/analyze/index.js";
import { loadSnapshotFile } from "../src/snapshot.js";
import { renderContext } from "../src/context.js";

const fixturePath = fileURLToPath(new URL("./fixtures/snapshot.small.json", import.meta.url));
const NOW = new Date("2026-09-16T00:00:00Z");

const snapshot = await loadSnapshotFile(fixturePath);
const findings = analyze(snapshot, { now: NOW });
const doc = renderContext(snapshot, findings, { now: NOW });

/** Body of one `## ` section, without its heading. */
function section(text, title) {
  const parts = text.split(/^## /m);
  const found = parts.find((p) => p.startsWith(`${title}\n`));
  assert.ok(found, `section "${title}" is missing`);
  return found.slice(title.length);
}

function countOccurrences(haystack, needle) {
  return haystack.split(needle).length - 1;
}

test("header names the instance and carries the preamble", () => {
  assert.ok(doc.startsWith("# Data context: Acme\n"));
  assert.match(doc, /This file is generated by metabase-audit\./);
  assert.match(doc, /Instance: https:\/\/metabase\.acme\.test/);
  assert.match(doc, /v0\.62\.3/);
  assert.match(doc, /Generated: 2026-09-16/);
});

test("sections appear once, in the documented order", () => {
  const order = [
    "## Instance overview",
    "## Data model",
    "## Relationships",
    "## Dashboards",
    "## Team and ownership",
    "## Key findings",
    "## Trusted queries",
    "## Glossary candidates",
    "## Notes for the reader",
  ];
  let cursor = -1;
  for (const heading of order) {
    const at = doc.indexOf(`\n${heading}\n`);
    assert.ok(at > cursor, `${heading} is missing or out of order`);
    assert.equal(countOccurrences(doc, `\n${heading}\n`), 1, `${heading} appears more than once`);
    cursor = at;
  }
});

test("instance overview reports counts, health and engines", () => {
  const body = section(doc, "Instance overview");
  assert.match(body, /- Databases: 1/);
  assert.match(body, /- Tables: 4/);
  assert.match(body, /- Active questions: 9/);
  assert.match(body, /- Dashboards: 3/);
  assert.match(body, /- Users known: 2/);
  assert.match(body, /- Health: C\+ \(51 of 100\)/);
  assert.match(body, /- Engines in use: postgres/);
});

test("data model renders the table header with usage and row count", () => {
  assert.ok(
    doc.includes("#### public.orders (5 questions, ~120,000 rows)"),
    "orders header with usage and row count",
  );
  assert.match(doc, /^One row per order$/m, "table description on its own line");
  assert.match(doc, /One row per order\n\n- id: Integer \[PK\]/, "columns start a new block");
  assert.match(doc, /#### public\.users \(5 questions, ~15,000 rows\)/);
});

test("data model lists columns with types, semantic types and FK targets", () => {
  const body = section(doc, "Data model");
  const line = body.split("\n").find((l) => l.startsWith("- user_id:"));
  assert.ok(line, "user_id column line");
  assert.match(line, /Integer/);
  assert.match(line, /\[FK\]/);
  assert.match(line, /-> users/);
  assert.match(body, /- amount: Decimal$/m, "plain column has no trailing markers");
  assert.match(body, /### Database: Warehouse \(postgres\)/);
});

test("data model honours the column cap", () => {
  const capped = renderContext(snapshot, findings, { now: NOW, maxColumns: 3 });
  assert.match(capped, /- \.\.\. 11 more columns/);
});

test("data model honours the table cap", () => {
  const capped = renderContext(snapshot, findings, { now: NOW, maxTablesPerDb: 2 });
  assert.match(capped, /and 2 more tables not listed/);
  assert.ok(!capped.includes("#### public.events"), "cut tables are not rendered");
});

test("tables without row counts or columns still render", () => {
  const patched = {
    ...snapshot,
    tables: snapshot.tables.map((t) =>
      t.id === 12 ? { ...t, rowCount: null, fields: [] } : t,
    ),
  };
  const out = renderContext(patched, findings, { now: NOW });
  assert.match(out, /#### public\.payments \(1 question, rows unknown\)/);
  assert.match(out, /- \(no column metadata in the snapshot\)/);
  assert.ok(!/\bundefined\b/.test(out));
});

test("relationships list declared foreign keys and inferred joins", () => {
  const body = section(doc, "Relationships");
  assert.match(body, /- orders\.user_id -> users\.id/);
  assert.match(body, /- payments\.order_id -> orders\.id/);
  assert.match(body, /Inferred from JOINs in saved questions:/);
  const inferred = body.split("Inferred from JOINs in saved questions:")[1];
  assert.match(inferred, /payments/);
  assert.match(inferred, /orders/);
  assert.match(inferred, /<->/);
});

test("dashboards render as a markdown table with links", () => {
  const body = section(doc, "Dashboards");
  assert.match(body, /\| Dashboard \| Questions \| Status \| Owner \| Views \|/);
  assert.match(body, /\| --- \| --- \| --- \| --- \| --- \|/);
  assert.match(body, /\| \[Exec\]\(https:\/\/metabase\.acme\.test\/dashboard\/20\) \| 2 \| healthy \| Jane Doe \| 50 \|/);
});

test("team and ownership renders creators", () => {
  const body = section(doc, "Team and ownership");
  assert.match(body, /\| Owner \| Questions \| Stale \|/);
  assert.match(body, /\| Bob Ray \| 3 \| 2 \|/);
  assert.match(body, /\| Jane Doe \| 3 \| 1 \|/);
});

test("team and ownership explains missing owner names", () => {
  const noCreators = renderContext(snapshot, { ...findings, creators: [] }, { now: NOW });
  assert.match(
    noCreators,
    /Owner names are not available \(the API key is not in the Administrators group\)\./,
  );
});

test("key findings carry between 4 and 8 numbered bullets", () => {
  const body = section(doc, "Key findings");
  const bullets = body.split("\n").filter((l) => l.startsWith("- "));
  assert.ok(bullets.length >= 4 && bullets.length <= 8, `got ${bullets.length} bullets`);
  for (const bullet of bullets) assert.match(bullet, /\d/, `no number in: ${bullet}`);
  assert.match(body, /C\+/);
  assert.match(body, /2 duplicate groups/);
  // The verb agrees with the leading count, not with the trailing noun.
  assert.match(body, /- 1 of 4 tables is never read by a saved question\./);
  assert.match(body, /- 5 of 9 active questions carry no description\./);
  assert.match(body, /- 2 of 3 dashboards carry a broken or a stale card\./);
});

test("trusted queries show the top card with its meta line and SQL", () => {
  const body = section(doc, "Trusted queries");
  assert.match(body, /### Revenue by month/);
  assert.match(
    body,
    /Views: 40\. Last used: 2026-09-11\. Collection: Finance\. Source: native SQL\./,
  );
  assert.match(body, /Monthly gross revenue from orders/);
  assert.match(body, /```sql\nSELECT date_trunc\('month', created_at\)/);
  assert.match(body, /Collection: none\./, "cards without a collection say none");
});

test("trusted queries respect the topQueries cap", () => {
  const one = renderContext(snapshot, findings, { now: NOW, topQueries: 1 });
  assert.equal(countOccurrences(one, "```sql"), 1);
  assert.match(one, /### Revenue by month/);
});

test("trusted queries skip archived cards and duplicate archive candidates", () => {
  assert.ok(!doc.includes("Archived thing"), "archived card");
  assert.ok(!doc.includes("Revenue by month (copy)"), "duplicate archive candidate id 2");
  assert.ok(!doc.includes("revenue_by_month_v2"), "duplicate archive candidate id 3");
});

test("trusted queries truncate long SQL", () => {
  const longSql = Array.from({ length: 80 }, (_, i) => `SELECT ${i} FROM orders`).join("\n");
  const patched = {
    ...snapshot,
    cards: snapshot.cards.map((c) => (c.id === 1 ? { ...c, sql: longSql } : c)),
  };
  const out = renderContext(patched, findings, { now: NOW, topQueries: 1 });
  assert.match(out, /-- truncated/);
  assert.ok(!out.includes("SELECT 70 FROM orders"), "lines past the cap are dropped");
});

test("sample database content is left out entirely", () => {
  assert.ok(!doc.includes("Sample Database"), "sample database");
  assert.ok(!doc.includes("PRODUCTS"), "sample table");
  assert.ok(!doc.includes("Sample card"), "sample card");
  assert.ok(!doc.includes("Sample User card"), "card authored by the Metabase demo user");
});

test("glossary candidates are lowercase and comma separated", () => {
  const body = section(doc, "Glossary candidates").trim();
  const last = body.split("\n").filter(Boolean).pop();
  assert.match(last, /revenue/);
  assert.match(last, /users/);
  assert.equal(last, last.toLowerCase());
  const terms = last.split(", ");
  assert.ok(terms.length <= 30, `got ${terms.length} terms`);
  assert.equal(new Set(terms).size, terms.length, "terms are distinct");
  assert.ok(!terms.includes("month"), "time grains are not business vocabulary");
  assert.ok(!terms.includes("card"), "Metabase's own nouns are not business vocabulary");
  assert.ok(terms.includes("churn"), "a business term counts even with one mention");
});

test("notes for the reader closes the file with a placeholder", () => {
  const body = section(doc, "Notes for the reader");
  assert.match(body, /The audit skills treat this section as ground truth\./);
  assert.match(body, /- \(your notes here\)/);
  assert.ok(doc.trimEnd().endsWith("- (your notes here)"), "notes section is last");
});

test("style rules: no dashes, no undefined, no NaN, tables have separators", () => {
  assert.ok(!doc.includes("\u2014"), "em dash");
  assert.ok(!doc.includes("\u2013"), "en dash");
  assert.ok(!/\bundefined\b/.test(doc), "undefined");
  assert.ok(!/\bNaN\b/.test(doc), "NaN");
  for (const line of doc.split("\n")) {
    if (line.startsWith("| ") && /\| (Dashboard|Owner) \|/.test(line)) {
      const next = doc.split("\n")[doc.split("\n").indexOf(line) + 1];
      assert.match(next, /^\| ---/, `header without separator: ${line}`);
    }
  }
});

test("em and en dashes in source text are rewritten, never passed through", () => {
  const patched = {
    ...snapshot,
    tables: snapshot.tables.map((t) => (t.id === 10 ? { ...t, description: "Orders \u2014 one row each" } : t)),
  };
  const out = renderContext(patched, findings, { now: NOW });
  assert.ok(!out.includes("\u2014"));
  assert.match(out, /Orders - one row each/);
});

test("pipes inside cell text are escaped", () => {
  const patched = {
    ...findings,
    creators: [{ id: 3, name: "A | B", totalCards: 1, activeCards: 1, staleCards: 0 }],
  };
  const out = renderContext(snapshot, patched, { now: NOW });
  assert.match(out, /\| A \\\| B \| 1 \| 0 \|/);
});

test("an empty snapshot renders without throwing", () => {
  const empty = {
    schemaVersion: 1,
    instance: { url: null, siteName: null, version: null },
    databases: [],
    tables: [],
    cards: [],
    dashboards: [],
    collections: [],
    users: [],
  };
  const emptyFindings = analyze(empty, { now: NOW });
  const out = renderContext(empty, emptyFindings, { now: NOW });
  assert.match(out, /^# Data context: /);
  assert.match(out, /No relationships detected\./);
  assert.match(out, /## Notes for the reader/);
  assert.ok(!/\bundefined\b/.test(out));
  assert.ok(!/\bNaN\b/.test(out));
});

test("renderContext is the only export", async () => {
  const mod = await import("../src/context.js");
  assert.deepEqual(Object.keys(mod).sort(), ["renderContext"]);
});

test("table usage survives a database name the renderer rewrites", () => {
  const patched = {
    ...snapshot,
    databases: snapshot.databases.map((d) => (d.id === 2 ? { ...d, name: "Prod – EU" } : d)),
  };
  const patchedFindings = analyze(patched, { now: NOW });
  const out = renderContext(patched, patchedFindings, { now: NOW });

  assert.match(out, /### Database: Prod - EU \(postgres\)/, "the en dash is rendered as a hyphen");
  assert.ok(!out.includes("–"), "no en dash survives into the document");
  assert.match(out, /#### public\.payments \(1 question, ~98,000 rows\)/, "usage is still found for the table");
  assert.match(out, /#### public\.orders \(5 questions, ~120,000 rows\)/);
});

test("Markdown in a question name is escaped, SQL blocks stay verbatim", () => {
  const hostile = {
    ...snapshot,
    cards: snapshot.cards.map((c) =>
      c.id === 1
        ? {
            ...c,
            name: "Revenue [click me](https://evil.example.com) `x`",
            description: "See [the doc](https://evil.example.com)",
            sql: "SELECT `amount` FROM orders",
          }
        : c,
    ),
  };
  const hostileFindings = analyze(hostile, { now: NOW });
  const out = renderContext(hostile, hostileFindings, { now: NOW });

  assert.ok(out.includes("### Revenue \\[click me\\](https://evil.example.com) \\`x\\`"), "brackets are escaped");
  assert.ok(out.includes("See \\[the doc\\]"), "descriptions are escaped too");
  assert.doesNotMatch(out, /[^\\]\]\(https:\/\/evil\.example\.com\)/, "no live link to the injected URL");
  assert.ok(out.includes("```sql\nSELECT `amount` FROM orders\n```"), "SQL is copied verbatim, backticks and all");
});
